// Auto-generated by Nour. DO NOT EDIT.

#include <stdbool.h>
#include <stddef.h>

typedef struct Target       Target;
typedef struct Executable   Executable;
typedef struct Library      Library;
typedef struct Project      Project;

typedef enum {
    T_EXECUTABLE,
    T_LIBRARY,
} TargetKind;

typedef enum {
    STATIC,
    SHARED,
    INTERFACE,
} LibraryType;

struct Target {
    TargetKind  kind;
    const char *name;
};

struct Executable {
    TargetKind   kind;
    const char  *name;
    const char  *root;
    const char **sources;
    const char **includes;
    const char **defines;
    const char **cflags;
    const char **ldflags;
    void       **deps;
};


struct Library {
    TargetKind   kind;
    const char  *name;
    LibraryType  type;
    const char **sources;
    const char **includes;
    const char **public_includes;
    const char **defines;
    const char **public_defines;
    const char **cflags;
    const char **ldflags;
    void       **deps;
};

struct Project {
    const char  *name;
    const char  *version;
    const char  *cc;
    const char  *build_dir;
    void       **targets;
};

// ─────────────────── Project Manifest ───────────────────
Executable app = {
    .kind = T_EXECUTABLE,
    .name = "app",
	.sources  = (const char*[]){ "src/*.c" , NULL },
	.includes = (const char*[]){ "include" , NULL },
	.defines  = (const char*[]){ "DEBUG" , NULL },
	.cflags   = (const char*[]){ "-O0", "-g" , NULL },
	.ldflags  = (const char*[]){ "-lm" , NULL },
};

Project AppProject = {
    .name = "AppProject",
	.version   = "0.1.0",
	.build_dir = "build",
	.targets   = (void*[]){ &app , NULL },
};

// ─────────────────── Entrypoint ───────────────────
Project *nour_get_project(void) { return &AppProject; }
