// Auto-generated by Nour. DO NOT EDIT.

#include <stdbool.h>
#include <stddef.h>

typedef struct Target	  Target;
typedef struct Executable Executable;
typedef struct Library	  Library;
typedef struct Project	  Project;

typedef enum {
	T_EXECUTABLE,
	T_LIBRARY,
} TargetKind;

typedef enum {
	STATIC,
	SHARED,
	INTERFACE,
} LibraryType;

struct Target {
	TargetKind	kind;
	const char *name;
};

struct Executable {
	TargetKind	 kind;
	const char	*name;
	const char	*root;
	const char **sources;
	const char **includes;
	const char **defines;
	const char **cflags;
	const char **ldflags;
	void	   **deps;
};

struct Library {
	TargetKind	 kind;
	const char	*name;
	LibraryType	 type;
	const char **sources;
	const char **includes;
	const char **public_includes;
	const char **defines;
	const char **public_defines;
	const char **cflags;
	const char **ldflags;
	void	   **deps;
};

struct Project {
	const char *name;
	const char *version;
	const char *cc;
	const char *build_dir;
	void	  **targets;
};

// ─────────────────── Project Manifest ───────────────────
// Main configuration
Executable server = {
    .kind = T_EXECUTABLE,
    .name = "server",
	// Source glob
	.sources = (const char*[]){
		"src/server.c",
		"src/net.c",
	    NULL
	},
	.cflags = (const char*[]){
		"-Wall",
		"-Wextra",
		"-std=c11",
	    NULL
	},
};

Project ServerProject = {
    .name = "ServerProject",
	.targets = (void*[]){ &server , NULL },
};

// ─────────────────── Entrypoint ───────────────────
Project *nour_get_project(void) { return &ServerProject; }
