#include "parser.h"
#include "nour_header.h"
#include <ctype.h>
#include <errno.h>
#include <stdio.h>
#include <string.h>

static const char *skip_ws(const char *s)
{
	while (*s && isspace((unsigned char)*s))
		++s;
	return s;
}

static bool check_declaration(const char *line, FILE *out, char *project_name)
{
	const char *trimmed = skip_ws(line);
	char		type[32], name[64];
	i32			n = 0;

	if (sscanf(trimmed, "%31s %63s = {%n", type, name, &n) != 2 || !n)
		return false;

	if (!strcmp(type, "Executable")) {
		fputs(line, out);
		fprintf(out, "    .kind = T_EXECUTABLE,\n");
		fprintf(out, "    .name = \"%s\",\n", name);
		return true;
	} else if (!strcmp(type, "Library")) {
		fputs(line, out);
		fprintf(out, "    .kind = T_LIBRARY,\n");
		fprintf(out, "    .name = \"%s\",\n", name);
		return true;
	} else if (!strcmp(type, "Project")) {
		fputs(line, out);
		fprintf(out, "    .name = \"%s\",\n", name);
		strncpy(project_name, name, 63);
		return true;
	}
	return false;
}

static const char *get_array_cast(const char *line)
{
	if (strstr(line, ".targets") || strstr(line, ".deps"))
		return "(void*[])";
	return "(const char*[])";
}

static char *find_closing_brace(char *s, char *last_ch)
{
	bool in_str = false;
	for (char *p = s; *p; ++p) {
		if (in_str && *p == '\\' && *(p + 1)) {
			++p;
			continue;
		}
		if (*p == '"')
			in_str = !in_str;
		if (!in_str && p[0] == '/' && p[1] == '/')
			break;
		if (!in_str && *p == '}')
			return p;
		if (!isspace((unsigned char)*p) && last_ch)
			*last_ch = *p;
	}
	return NULL;
}

static void attach_header(FILE *out)
{
	fprintf(out, "// Auto-generated by Nour. DO NOT EDIT.\n");
	fputs(strchr((char *)include_nour_h, '\n') + 1, out);
	fprintf(out, "\n// ─────────────────── Project Manifest ───────────────────\n");
}

static void attach_entrypoint(FILE *out, const char *project_name)
{
	if (project_name[0]) {
		fprintf(out, "\n// ─────────────────── Entrypoint ───────────────────\n");
		fprintf(out, "Project *nour_get_project(void) { return &%s; }\n", project_name);
	}
}

Result preprocess(const char *input_path, const char *output_path)
{
	FILE *in = fopen(input_path, "r");
	if (!in) {
		return Err("Failed to open input file '%s': %s", input_path, strerror(errno));
	}

	FILE *out = fopen(output_path, "w");
	if (!out) {
		fclose(in);
		return Err("Failed to create output file '%s': %s", output_path, strerror(errno));
	}

	attach_header(out);

	char line[1024];
	char project_name[64] = { 0 };
	bool in_array		  = false;
	char last_ch		  = 0;

	while (fgets(line, sizeof(line), in)) {
		const char *trimmed = skip_ws(line);
		if (trimmed[0] == '/' && trimmed[1] == '/') {
			fputs(line, out);
			continue;
		}

		if (!in_array && check_declaration(line, out, project_name))
			continue;

		if (in_array) {
			char *close_brace = find_closing_brace(line, &last_ch);

			if (close_brace) {
				*close_brace	= '\0';
				bool need_comma = last_ch && last_ch != ',';
				fprintf(out, "%s%s    NULL\n\t}%s", line, need_comma ? "," : "", close_brace + 1);
				in_array = false;
			} else {
				fputs(line, out);
			}
			continue;
		}

		char *open_brace = strchr(line, '{');
		char *equal		 = strchr(line, '=');
		if (open_brace && equal && open_brace > equal) {
			const char *cast		= get_array_cast(line);
			char	   *close_brace = find_closing_brace(open_brace + 1, NULL);

			if (close_brace) {
				*open_brace	 = '\0';
				*close_brace = '\0';
				const char *body = open_brace + 1;
				const char *p	 = close_brace - 1;
				while (p >= body && isspace((unsigned char)*p)) {
					--p;
				}
				bool		empty			   = (p < body);
				bool		has_trailing_comma = (!empty && *p == ',');
				const char *sep				   = (empty || has_trailing_comma) ? " " : ", ";
				fprintf(out, "%s%s{%s%sNULL }%s", line, cast, body, sep, close_brace + 1);
			} else {
				*open_brace = '\0';
				char *after = open_brace + 1;
				in_array	= true;
				last_ch		= 0;
				find_closing_brace(after, &last_ch);
				fprintf(out, "%s%s{%s%s", line, cast, after, strchr(after, '\n') ? "" : "\n");
			}
			continue;
		}
		fputs(line, out);
	}

	fclose(in);

	if (in_array) {
		fclose(out);
		remove(output_path);
		return Err("Unclosed array in '%s'", input_path);
	}

	if (!project_name[0]) {
		fclose(out);
		remove(output_path);
		return Err("No Project declaration found in '%s'", input_path);
	}

	attach_entrypoint(out, project_name);
	fclose(out);
	return Ok(NULL);
}
